// vue/src/components/Time.vue
<template>
  <div>
    {{time}}
  </div>
</template>

<script>
  export default {
    data() {
      return {
        time: new Date().toString(),
        t: null
      }
    },
    created() {
      this.updateTime()
    },
    methods: {
      updateTime() {
        var that = this
        this.t = setInterval(() => {
          that.time = new Date().toString()
        }, 1000)
      }
    }
  }
</script>

// react-router(v3)/src/components/Time.js
import React, { Component } from 'react'
import { Link } from 'react-router'

class Time extends Component {
  constructor(props) {
    super(props)
    this.state = {
      time: new Date().toString(),
      t:null
    }
  }
  componentDidMount() {
    this.updateTime()
  }
  componentWillUnmount() {
    clearInterval(this.state.t)
  }
  render() {
    return (
      <div>
        {this.state.time}
        <Link to='/'>home</Link>
      </div>
    )
  }
  updateTime() {
    this.state.t = setInterval(() => {
      this.setState({time: new Date().toString()})
    }, 1000)
  }
}
export default Time
