// vue/src/components/Time.vue
<template>
  <div>
    {{time}}
  </div>
</template>

<script>
  export default {
    data() {
      return {
        time: new Date().toString(),
        t: null
      }
    },
    created() {
      this.updateTime()
    },
    methods: {
      updateTime() {
        var that = this
        this.t = setInterval(() => {
          that.time = new Date().toString()
        }, 1000)
      }
    }
  }
</script>

// react/src/Time.js
import React, { Component } from 'react'
class Time extends Component {
  constructor(props) {
    super(props)
    this.state = {
      time:new Date().toString()
    }
  }
  componentDidMount() {
    this.updateTime()
  }
  render() {
    return (
      <div>
        {this.state.time}
        <button onClick={() => this.props.alertTime(this.state.time)}>alertTime</button>
      </div>
    )
  }
  updateTime() {
    var t = setInterval(() => {
      this.setState({time: new Date().toString()})
    }, 1000)
  }
}
export default Time
